version: "3.8"

services:
  ml-backend:
    platform: linux/amd64
    container_name: ocr-backend
    image: registry-dev.tcgroup.vn/lstdml_ocr_line_backend
    build: .
    environment:
      - MODEL_DIR=/data/models
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
      - ANY=PARAMETER
    ports:
      - "9090:9090"
